### ISSUE TITLE
executable does not run from out-ouf-source build

### ISSUE THREAD

**Issue by bregma** [bregma/no-dice#4]
Steps to reproduce:

1. from $top_srcdir, run` mkdir build; cd build`
2. ` ../bootstrap && make`
3. `nodice/no-dice`

The result is the program fails to run with the following error.

```
no-dice 0.3.0
*** ERROR exception caught: error in FT_New_Face
```

**Comment by BrandonSchaefer** [comment]
This requires you to run ./nodice/no-dice from the root dir, since in font.cpp:
#define DATA_DIR "./"
If you run no-dice from its source directory it fails to find the assets folder. Could use autotools to generate a path to the local assets folder, or the root source directory.

You could also change the DATA_DIR to be ../ which would allow you to run ./no-dice from the nodice dir :)
